export const pageStyles = {
  page: {
    padding: "28px",
    borderRadius: "16px",
    background: "var(--box-bg)",
    minHeight: "320px",
    boxShadow: "var(--shadow)",
    border: "1px solid var(--line)",
  },
  topo: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "16px",
    marginBottom: "20px",
    flexWrap: "wrap",
  },
  titulo: {
    color: "var(--text)",
    margin: 0,
    fontSize: "24px",
    fontWeight: 800,
  },
  subtitulo: {
    color: "var(--muted)",
    marginTop: "8px",
    marginBottom: 0,
  },
  btnPrimario: {
    padding: "12px 20px",
    borderRadius: "10px",
    border: "none",
    background: "linear-gradient(135deg, var(--primary) 0%, #2f86ff 100%)",
    color: "#fff",
    fontWeight: 700,
    cursor: "pointer",
    fontSize: "14px",
    boxShadow: "0 12px 24px rgba(11, 115, 255, 0.24)",
  },
  btnSecundario: {
    padding: "10px 16px",
    borderRadius: "8px",
    border: "1px solid var(--line)",
    background: "var(--field-bg)",
    color: "var(--text)",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: 700,
  },
  btnPerigo: {
    padding: "10px 16px",
    borderRadius: "8px",
    border: "none",
    background: "#dc2626",
    color: "#fff",
    cursor: "pointer",
    fontSize: "13px",
  },
  filtrosArea: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: "16px",
    marginBottom: "22px",
  },
  filtroGrupo: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  label: {
    color: "var(--text)",
    fontSize: "14px",
    opacity: 0.8,
  },
  input: {
    padding: "13px 16px",
    borderRadius: "10px",
    border: "1px solid var(--line)",
    background: "var(--field-bg)",
    color: "var(--text)",
    fontSize: "14px",
    width: "100%",
    boxSizing: "border-box",
    outline: "none",
  },
  select: {
    padding: "13px 16px",
    borderRadius: "10px",
    border: "1px solid var(--line)",
    background: "var(--field-bg)",
    color: "var(--text)",
    fontSize: "14px",
    cursor: "pointer",
    width: "100%",
    outline: "none",
  },
  textarea: {
    padding: "13px 16px",
    borderRadius: "10px",
    border: "1px solid var(--line)",
    background: "var(--field-bg)",
    color: "var(--text)",
    fontSize: "14px",
    width: "100%",
    minHeight: "80px",
    resize: "vertical",
    boxSizing: "border-box",
    fontFamily: "inherit",
  },
  tabelaBox: {
    background: "var(--box-bg)",
    borderRadius: "16px",
    padding: "20px",
    boxShadow: "var(--shadow-soft)",
    border: "1px solid var(--line)",
    overflow: "auto",
    height: "420px",
    minHeight: "420px",
  },
  tabela: {
    width: "100%",
    borderCollapse: "collapse",
    color: "var(--text)",
  },
  th: {
    textAlign: "left",
    padding: "14px 12px",
    borderBottom: "1px solid var(--line)",
    whiteSpace: "nowrap",
    fontSize: "13px",
    color: "var(--text)",
  },
  td: {
    padding: "16px 12px",
    borderBottom: "1px solid var(--line)",
    color: "var(--muted)",
  },
  acoes: {
    display: "flex",
    gap: "6px",
    flexWrap: "nowrap",
    alignItems: "center",
  },
  vazio: {
    color: "var(--text)",
    opacity: 0.7,
    marginTop: "16px",
    textAlign: "center",
  },
  erro: {
    color: "#dc2626",
    fontSize: "14px",
    margin: "8px 0",
  },
  sucesso: {
    color: "#16a34a",
    fontSize: "14px",
    margin: "8px 0",
  },
  formGrupo: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    marginBottom: "16px",
  },
  formAcoes: {
    display: "flex",
    gap: "10px",
    justifyContent: "flex-end",
    marginTop: "18px",
    flexWrap: "wrap",
  },
  carregando: {
    color: "var(--text)",
    opacity: 0.7,
    padding: "40px",
    textAlign: "center",
  },
};
