export const pageStyles = {
  page: {
    padding: "28px",
    borderRadius: "18px",
    background: "var(--box-bg)",
    minHeight: "320px",
  },
  topo: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "16px",
    marginBottom: "20px",
    flexWrap: "wrap",
  },
  titulo: {
    color: "var(--text)",
    margin: 0,
    fontSize: "28px",
  },
  subtitulo: {
    color: "var(--text)",
    opacity: 0.7,
    marginTop: "8px",
    marginBottom: 0,
  },
  btnPrimario: {
    padding: "10px 18px",
    borderRadius: "10px",
    border: "none",
    background: "#7fc1f5",
    color: "#fff",
    fontWeight: 600,
    cursor: "pointer",
    fontSize: "14px",
  },
  btnSecundario: {
    padding: "8px 14px",
    borderRadius: "8px",
    border: "1px solid #cbd5e1",
    background: "var(--bg)",
    color: "var(--text)",
    cursor: "pointer",
    fontSize: "13px",
  },
  btnPerigo: {
    padding: "8px 14px",
    borderRadius: "8px",
    border: "none",
    background: "#dc2626",
    color: "#fff",
    cursor: "pointer",
    fontSize: "13px",
  },
  filtrosArea: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: "16px",
    marginBottom: "22px",
  },
  filtroGrupo: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  label: {
    color: "var(--text)",
    fontSize: "14px",
    opacity: 0.8,
  },
  input: {
    padding: "10px 14px",
    borderRadius: "10px",
    border: "1px solid #cbd5e1",
    background: "var(--bg)",
    color: "var(--text)",
    fontSize: "14px",
    width: "100%",
    boxSizing: "border-box",
  },
  select: {
    padding: "10px 14px",
    borderRadius: "10px",
    border: "1px solid #cbd5e1",
    background: "var(--bg)",
    color: "var(--text)",
    fontSize: "14px",
    cursor: "pointer",
    width: "100%",
  },
  textarea: {
    padding: "10px 14px",
    borderRadius: "10px",
    border: "1px solid #cbd5e1",
    background: "var(--bg)",
    color: "var(--text)",
    fontSize: "14px",
    width: "100%",
    minHeight: "80px",
    resize: "vertical",
    boxSizing: "border-box",
    fontFamily: "inherit",
  },
  tabelaBox: {
    background: "var(--bg)",
    borderRadius: "14px",
    padding: "20px",
    boxShadow: "0 2px 8px rgba(0,0,0,0.08)",
    overflowX: "auto",
  },
  tabela: {
    width: "100%",
    borderCollapse: "collapse",
    color: "var(--text)",
  },
  th: {
    textAlign: "left",
    padding: "12px",
    borderBottom: "1px solid #ccc",
    whiteSpace: "nowrap",
  },
  td: {
    padding: "12px",
    borderBottom: "1px solid rgba(180,180,180,0.3)",
  },
  acoes: {
    display: "flex",
    gap: "6px",
    flexWrap: "nowrap",
    alignItems: "center",
  },
  vazio: {
    color: "var(--text)",
    opacity: 0.7,
    marginTop: "16px",
    textAlign: "center",
  },
  erro: {
    color: "#dc2626",
    fontSize: "14px",
    margin: "8px 0",
  },
  sucesso: {
    color: "#16a34a",
    fontSize: "14px",
    margin: "8px 0",
  },
  formGrupo: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    marginBottom: "14px",
  },
  formAcoes: {
    display: "flex",
    gap: "10px",
    justifyContent: "flex-end",
    marginTop: "18px",
    flexWrap: "wrap",
  },
  carregando: {
    color: "var(--text)",
    opacity: 0.7,
    padding: "40px",
    textAlign: "center",
  },
};
